# Utilizar una imagen base de Node.js
FROM node:14

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar el archivo 'package.json' y 'package-lock.json' (si está disponible)
COPY package*.json ./

# Instalar dependencias del proyecto
RUN npm install

RUN npm install cors

# Copiar los archivos del proyecto al directorio de trabajo del contenedor
COPY . .

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 3003

# Comando para ejecutar la aplicación
CMD ["node", "apiGateway.js"]
