# Usar una imagen base de Node.js
FROM node:14

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de la aplicación al contenedor
COPY gestorLogs.js package*.json /app/

# Instalar las dependencias de la aplicación
RUN npm install

RUN npm install cors

# Comando para ejecutar la aplicación
CMD ["node", "gestorLogs.js"]
