version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    env_file:
      - redis.env

  consumidor:
    build:
      context: .
      dockerfile: Dockerfile.consumidor
    env_file:
      - logs.env
    ports:
      - "4001:4001"
    depends_on:
      - redis

  perfil:
    build:
      context: .
      dockerfile: Dockerfile.perfil
    ports:
      - "3002:3002"
    volumes:
      - ./data:/data
    depends_on:
      - redis

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.apiGateway
    ports:
      - "3003:3003"
    depends_on:
      - app
      - redis

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
