openapi: 3.0.0
info:
  title: API de Gestión de Perfiles
  description: API para manejar y consultar perfiles de usuarios.
  version: "1.0.0"
servers:
  - url: http://localhost:3002
    description: Servidor de desarrollo local

paths:
  /perfil/{id}:
    get:
      summary: Obtener perfil de usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del perfil de usuario
      responses:
        '200':
          description: Perfil de usuario obtenido con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerfilUsuario'
        '404':
          description: Usuario no encontrado
        '500':
          description: Error al consultar la base de datos
    put:
      summary: Actualizar perfil de usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del perfil de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerfilUsuario'
      responses:
        '200':
          description: Perfil de usuario actualizado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPSuccess'
        '400':
          description: Datos de perfil no válidos
        '401':
          description: Token no válido
        '403':
          description: No tienes permiso para actualizar este perfil
        '500':
          description: Error al actualizar el perfil

  /perfiles:
    get:
      summary: Listar todos los perfiles de usuario
      responses:
        '200':
          description: Lista de perfiles de usuario
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PerfilUsuario'
        '500':
          description: Error al recuperar los perfiles

  /health:
    get:
      summary: Verificar el estado general del servicio
      responses:
        '200':
          description: El servicio está operativo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'

  /health/ready:
    get:
      summary: Verificar si el servicio está listo para manejar tráfico
      responses:
        '200':
          description: El servicio está listo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        '500':
          description: El servicio no está listo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'

  /health/live:
    get:
      summary: Verificar si el servicio está vivo
      responses:
        '200':
          description: El servicio está vivo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'

components:
  schemas:
    PerfilUsuario:
      type: object
      properties:
        id:
          type: integer
        url_personal:
          type: string
        apodo:
          type: string
        info_contacto:
          type: string
        direccion:
          type: string
        biografia:
          type: string
        organizacion:
          type: string
        pais_residencia:
          type: string
        redes_sociales:
          type: array
          items:
            type: string
      required:
        - id

    HealthStatus:
      type: object
      properties:
        status:
          type: string
        error:
          type: string
          nullable: true

    HTTPError:
      type: object
      properties:
        error:
          type: string

    HTTPSuccess:
      type: object
      properties:
        message:
          type: string

securitySchemes:
  BearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT
