global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'gestor_logs'
    static_configs:
      - targets: ['consumidor:4001']

  - job_name: 'app_autenticacion'
    static_configs:
      - targets: ['app:3000']

  - job_name: 'perfil'
    static_configs:
      - targets: ['perfil:3002']

  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api-gateway:3003']
